# Generated by Django 2.1.2 on 2018-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', models.CharField(max_length=1000, verbose_name='내용')),
                ('writer', models.CharField(max_length=50, verbose_name='글쓴이')),
                ('pwd', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('hit', models.IntegerField(default=0, verbose_name='점수')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='처음 글쓴 시간')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
        ),
    ]
